modLoader="javafml"
loaderVersion="[36,)"
license="who cares"
[[mods]]
modId="bettas"
version="${file.jarVersion}"
displayName="ğ““ragN's Betta Fish Mod"
logoFile="replaceme.png"
credits=""
authors="ğ““ragN, EvangeliX"
description='''

'''
[[dependencies.bettas]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bettas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
